language: python
python:

  - "2.7"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - pip install -r training_requirements.txt
  - pip install coveralls

script:

  - coverage run --omit=*.virtualenvs*,*virtualenv* code/training_evaluation/train.py test

after_success:
  coveralls

sudo: enabled
dist: trusty
